name: run_script
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib
          pip install ruff 
          pip install pytest
      - name: Ruff
        run: ruff format main_ref.py
      - name: Unit Test
        run: pytest test_main.py
      - name: Comments
        run:  echo "This is a very good code (No!)"
      - name: Run Code
        run: python main.py
